version: '3'
services:
  tf:
    environment:
      - PYTHONPATH=.
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    build:
      context: .
      args:
        - CI_USER_TOKEN=${CI_USER_TOKEN}
        - DEV_tensorflow_v2_examples=1
    ports:
      - '8157:8888'
      - '6009:6666'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix #Static - needed to display atom on your host
      - .:/tf
      - /home/andy/data/:/tf/data
      - ./src/notebooks/:/tf/notebooks