version: '3'
services:
  tf:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CSCI_SALT=${CSCI_SALT}
      - PYTHONPATH=.
    build:
      context: .
      args:
        - CI_USER_TOKEN=${CI_USER_TOKEN}
        - DEV_tensorflow_v2_examples=1
    ports:
      - '8157:8888'
      - '6009:6666'
    volumes:
      - .:/tf
      - /home/andy/data/:/tf/data
      - ./src/notebooks/:/tf/notebooks